### ISSUE TITLE
document jslint versions

### ISSUE THREAD

**Issue by MartinMa** [ajhyndman/vscode-jslint#3]
What are the available options for the setting "jslint.versions"?

The example only states three options:
- `"jslint.version": "es6"`
- `"jslint.version": "latest"`
- `"jslint.version": "2013-02-03"`

The JSLint website doesn't offer a version history. I guess `es5` is another valid option? The latest version doesn't work with my codebase. Apparently some options have been removed.

**Comment by MartinMa** [comment]
Ok after some digging I found out that it (probably) relates to the filenames of the files in this folder (at least partly): [https://github.com/reid/node-jslint/tree/master/lib](https://github.com/reid/node-jslint/tree/master/lib)

Which would be:
- `"2012-02-03"`
- `"2013-02-03"`
- `"2013-08-13"`
- `"2013-08-26"`
- `"2013-09-22"`
- `"2013-11-23"`
- `"2014-01-26"`
- `"2014-02-06"`
- `"2014-04-21"`
- `"2014-07-08"` (`"es5"`)
- `"2015-05-08"`
- `"2016-05-13"`
- `"2016-07-13"` (`"es6"`)
- `"es5"` (seems to be an alias for `"2014-07-08"`)
- `"es6"` (seems to be an alias for `"2016-07-13"`)
- `"latest"` (has the date `"2015-10-29"`, which doesn't occur in any filename)

**Comment by ajhyndman** [comment]
@MartinMa Yep, you got it right.  I thought about linking directly to that directory, but It feels risky to link to a subdirectory in the source of another project as a part of my primary documentation.  :D

Do you have any suggestions about what might have helped you figure this part out more easily?

**Comment by MartinMa** [comment]
Maybe it would help to link to the `node-jslint` project, because I started looking at jslint.com at first.

I think it refers to the `--edition` option of `node-jslint`, right?

**Comment by ajhyndman** [comment]
@MartinMa It does, that's exactly right.  I did link to this page: https://www.npmjs.com/package/jslint, which is the official npm module README.  Do you think it would have helped to link to the github repository directly?

**Comment by MartinMa** [comment]
@ajhyndman I just revisited the marketplace and all relevant information is there. Perfect, thanks. :+1:

I think I might have been blind. Closing.

**Comment by ajhyndman** [comment]
Thanks for garbage-collecting the issues @MartinMa.  :+1:
