### ISSUE TITLE
"incorrect" tab/spaces warnings

### ISSUE THREAD

**Issue by MartinMa** [ajhyndman/vscode-jslint#4]
My working environment is configured with an indent of two spaces. The plugin seems to expect a four spaces indent though. This leads to jslint warnings like `Expected 'ngAnimate' at column 5, not column 3.` all over the place.

I don't want to turn my whole source code inside out. I even changed the jslint.version to `"es5"`. Is there a way to have 2 spaces indentation **and** use jslint?

**Comment by ajhyndman** [comment]
Hey @MartinMa, thanks for your interest!

JSLint's configuration is documented at http://www.jslint.com/help.html.  

I suggest trying the rule:
`/*jslint white: true */`

You can add that line as a comment at the top of files you wish it to apply to, or in a `jslint.conf` file in your project's root directory as follows:

``` js

{
    "white": true,
    "predef": "module, require"
}

```

This plugin is a pretty shallow wrapper that runs node-jslint and displays feedback in your editor while you work.  All of the configuration options that apply to node-jslint should work exactly as described in [their documentation](https://www.npmjs.com/package/jslint).

I hope that helps!

**Comment by MartinMa** [comment]
Hi @ajhyndman thanks for your extensive answer! The coherences are clear now.

Unfortunately with `/* jslint white: true */` I'd lose all other white space rules as well. I like the strictness of JSLint here. I'm note sure if it has always been that way with the _4 spaces rule_. I think I will take a look at some older releases of jslint.

**Comment by ajhyndman** [comment]
I think you're right about some older versions of jslint supporting an `indent: 2` option.

A couple alternatives to downgrading JSLint:
- [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) seems to be the current de-facto linter of preference for big projects.  It has good support for ES6 and React features.  The big downside is learning all of configuration to get going.
- For an alternative, but equally opinionated take on good coding style, you might check out [JS Standard Style](https://github.com/feross/standard).  StandardJS expects two-space indentation.
- Run [JS Code Shift](https://github.com/facebook/jscodeshift) over all of your code to change the indentation (or make any other style change you'd like!)

**Comment by MartinMa** [comment]
Ah the `indent: 2` option. I think I have seen this before. Checking this out.

Thanks for all the alternatives, too. I already experimented a little bit with ESLint and like the customizability. Might pick up the [xo rulset](https://github.com/sindresorhus/eslint-config-xo) and start from there.
