### ISSUE TITLE
can i use my vscode with php + html + js ? 

### ISSUE THREAD

**Issue by MiguelQueiroz** [ajhyndman/vscode-jslint#5]

**Comment by ajhyndman** [comment]
I'm afraid that JSLint won't lint files that aren't entirely javascript.  Linting of inline javascript in an HTML (or PHP) file is not supported.  Is that what you're asking?

**Comment by MiguelQueiroz** [comment]
Yep thats what  said. Because many times some type of webapps are a javascript inline althought that is not very recomended.

**Comment by ajhyndman** [comment]
Here's a link to Crockford's decision to remove support for linting of inline Javascript:

https://groups.yahoo.com/neo/groups/jslint_com/conversations/messages/3170

In case you don't have a Yahoo account:

![image](https://cloud.githubusercontent.com/assets/11449340/20243202/c687865c-a9a1-11e6-8710-d4f921f7c9f6.png)
